# Generated by Django 5.2 on 2025-05-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_role_department_role_position_role_position_level'),
        ('users', '0002_user_app_running_user_company_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_status_changed', 'Company Status Changed'), ('admin_assigned', 'Admin Role Assigned'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('employee_status_changed', 'Employee Status Changed')], max_length=50)),
                ('performed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='companies.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
