# Generated by Django 5.2 on 2025-05-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_teamcategory_team_teammember'),
        ('employees', '0003_attendance_attendancelog_employeefacedata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employeeprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeelocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
