# Generated by Django 5.2 on 2025-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_attendance_company_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershift',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usershift',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usershift',
            name='positional_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usershift',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
