# Generated by Django 5.2 on 2025-05-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Tech'), (2, 'Educational')], default=1)),
                ('user_limit', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('address_line', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('company_type', models.CharField(choices=[('tech', 'Tech'), ('educational', 'Educational')], max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('self', 'Self Only'), ('department', 'Department'), ('team', 'Team'), ('company', 'Company-wide')], default='department', help_text='Determines the scope of data this role can access', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.company')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='companies.permission')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
    ]
